title: Neural Cellular Automata (NCA)
logo: nca_logo.png
description: Research Projects on NCAs  
show_downloads: false
google_analytics:
markdown: kramdown
kramdown:
  math_engine: mathjax
theme: jekyll-theme-minimal
